name: kmou
description: 한국해양대학교 공지사항, 학식, 학사일정 조회 라이브러리
version: 1.0.0
repository: https://github.com/Beta5051/kmou_dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  html: ^0.15.2
  http: ^0.13.6
  intl: ^0.18.1